"""add closedChats column

Revision ID: db07dc88f501
Revises: 2978f878ad2c
Create Date: 2025-08-26 15:19:49.898188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'db07dc88f501'
down_revision: Union[str, Sequence[str], None] = '2978f878ad2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column("closedChats", sa.JSON(), default=list, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'closedChats')
    # ### end Alembic commands ###
